machine:
    environment:
        ROOT_DIR: /tmp/mbed-greenlight

version: 2
jobs:
    build:
        docker:
            - image: ubuntu
        steps:
            - run:
                name: Install System Dependencies
                command:  apt-get update -qq &&  apt-get install -y python python-pip wget git
            - checkout
            - run:
                name: Install dependecies
                command: pip install nose requests
            - run:
                name: Run update test
                command: nosetests -s
            - run:
                name: Commit changes
                command: |
                    git config --global user.email michael.bartling@arm.com
                    git config --global user.name Michael Bartling
                    mkdir -p ~/.ssh
                    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
                    git add mbed-cli.rb
                    git commit -m "Updated release"
                    git push
